const hmtai = require("./hmtai");

const data = {
  wallpaper: hmtai.wallpaper(),
  "mobile-wallpaper": hmtai.mobileWallpaper(),
  neko: hmtai.neko(),
  jahy: hmtai.jahy(),
  lick: hmtai.lick(),
  slap: hmtai.slap(),
  depression: hmtai.depression(),
  legs: hmtai.legs(),
  christmas: hmtai.christmas(),
  ass: hmtai.nsfw.ass(),
  bdsm: hmtai.nsfw.bdsm(),
  cum: hmtai.nsfw.cum(),
  creampie: hmtai.nsfw.creampie(),
  manga: hmtai.nsfw.manga(),
  femdom: hmtai.nsfw.femdom(),
  hentai: hmtai.nsfw.hentai(),
  incest: hmtai.nsfw.incest(),
  masturbation: hmtai.nsfw.masturbation(),
  public: hmtai.nsfw.public(),
  ero: hmtai.nsfw.ero(),
  orgy: hmtai.nsfw.orgy(),
  elves: hmtai.nsfw.elves(),
  yuri: hmtai.nsfw.yuri(),
  pantsu: hmtai.nsfw.pantsu(),
  glasses: hmtai.nsfw.glasses(),
  cuckold: hmtai.nsfw.cuckold(),
  blowjob: hmtai.nsfw.blowjob(),
  boobjob: hmtai.nsfw.boobjob(),
  foot: hmtai.nsfw.foot(),
  thighs: hmtai.nsfw.thighs(),
  ahegao: hmtai.nsfw.ahegao(),
  uniform: hmtai.nsfw.uniform(),
  "gang-Bang": hmtai.nsfw.gangbang(),
  tentacles: hmtai.nsfw.tentacles(),
  gif: hmtai.nsfw.gif(),
  "nsfw Neko": hmtai.nsfw.nsfwNeko(),
  "nsfw-mobile-wallpaper": hmtai.nsfw.nsfwMobileWallpaper(),
  "zettai-ryouiki": hmtai.nsfw.zettaiRyouiki(),
  "nsfw-christmas": hmtai.nsfw.nsfwChristmas(),
};


module.exports = data;
